### PR TITLE
turso

### PR DESCRIPTION
**Pull request by bchilcott**
not an "official" provider, idk if this is a good idea
https://github.com/jpedroh/terraform-provider-turso

### CODE REVIEW

**Comment by thdxr** [comment]
embarrassing series of failures with this merge attempt...
i might switch off json too annoying to add stuff properly

**Comment by bchilcott** [comment]
@thdxr this provider isn't on opentofu - can we specify the terraform provider registry explicitly?

**Comment by bchilcott** [comment]
The pulumi tool would allow it:
https://www.pulumi.com/blog/any-terraform-provider/#:~:text=or%20a%20fully%2Dqualified%20reference%20to%20any%20Terraform%20Registry%20API%2Dcompatible%20server

**Comment by thdxr** [comment]
yeah i'm looking to see how to switch the default provider registry

**Comment by thdxr** [comment]
figured it out just need to specify like this `registry.terraform.io/jpedroh/turso`

**Comment by bchilcott** [comment]
already opened #2

**Pull request merged**
